package cn.com.cslc.aw.agent.domain;
// Generated 2017-9-14 11:07:50 by Hibernate Tools 5.1.2.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import cn.com.cslc.aw.core.common.domain.BaseEntity;

/**
 * SysAgentState generated by hbm2java
 */
@Entity
@Table(name = "SYS_AGENT_STATE")
public class SysAgentState extends BaseEntity {

	private String code;
	private String name;


	@Column(name = "CODE", length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "NAME", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
