package cn.com.cslc.aw.agent.domain;
// Generated 2017-9-14 11:07:50 by Hibernate Tools 5.1.2.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import cn.com.cslc.aw.core.common.domain.BaseEntity;
import cn.com.cslc.aw.core.common.domain.SysProvince;

/**
 * SysAgent generated by hbm2java
 */
@Entity
@Table(name = "SYS_AGENT")
public class SysAgent extends BaseEntity {

	private SysAgentState sysAgentState;
	private String code;
	private String name;
	private Date createDate;
	private Date lastOperDate;
	private String provinceNo;
	private SysProvince sysProvince;
	
	private Set<SysOrgAgent> sysOrgAgents = new HashSet<SysOrgAgent>(0);

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATE_ID")
	public SysAgentState getSysAgentState() {
		return this.sysAgentState;
	}

	public void setSysAgentState(SysAgentState sysAgentState) {
		this.sysAgentState = sysAgentState;
	}

	@Column(name = "CODE", length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_OPER_DATE", length = 19)
	public Date getLastOperDate() {
		return this.lastOperDate;
	}

	public void setLastOperDate(Date lastOperDate) {
		this.lastOperDate = lastOperDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysAgent")
	public Set<SysOrgAgent> getSysOrgAgents() {
		return this.sysOrgAgents;
	}

	public void setSysOrgAgents(Set<SysOrgAgent> sysOrgAgents) {
		this.sysOrgAgents = sysOrgAgents;
	}

	@Column(name = "PROVINCE_NO", length = 6)
	public String getProvinceNo() {
		return provinceNo;
	}

	public void setProvinceNo(String provinceNo) {
		this.provinceNo = provinceNo;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "province_id")
	public SysProvince getSysProvince() {
		return this.sysProvince;
	}

	public void setSysProvince(SysProvince sysProvince) {
		this.sysProvince = sysProvince;
	}
}
