package cn.com.cslc.aw.agent.domain;
// Generated 2017-9-14 11:15:03 by Hibernate Tools 5.1.2.Final

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import cn.com.cslc.aw.agent.domain.SysAgent;
import cn.com.cslc.aw.core.common.domain.BaseEntity;
import cn.com.cslc.aw.core.common.domain.SysOrg;

/**
 * SysOrgAgent generated by hbm2java
 */
@Entity
@Table(name = "SYS_ORG_AGENT")
public class SysOrgAgent extends BaseEntity {

	private SysOrg sysOrg;
	private SysAgent sysAgent;


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORG_ID")
	public SysOrg getSysOrg() {
		return this.sysOrg;
	}

	public void setSysOrg(SysOrg sysOrg) {
		this.sysOrg = sysOrg;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AGENT_ID")
	public SysAgent getSysAgent() {
		return this.sysAgent;
	}

	public void setSysAgent(SysAgent sysAgent) {
		this.sysAgent = sysAgent;
	}

}
