--1、删除原有表结构


--2、新建的表结构

ALTER TABLE SYS_AGENT 
DROP CONSTRAINT AGENT_FK_PROVINCE;

ALTER TABLE SYS_AGENT 
DROP COLUMN PROVINCE_ID;

ALTER TABLE SYS_AGENT 
ADD (PROVINCE_ID NUMBER(19) );

ALTER TABLE SYS_AGENT
ADD CONSTRAINT AGENT_FK_PROVINCE FOREIGN KEY
(
  PROVINCE_ID 
)
REFERENCES SYS_PROVINCE
(
  ID 
)
ENABLE;

ALTER TABLE SYS_ORG 
DROP CONSTRAINT ORG_FK_TYPE;

DROP TABLE SYS_ORG_TYPE;
CREATE TABLE SYS_ORG_TYPE 
(
  ID NUMBER(19) NOT NULL 
, CODE VARCHAR2(10) 
, NAME VARCHAR2(20) 
, CONSTRAINT SYS_ORG_TYPE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE SYS_ORG 
DROP CONSTRAINT ORG_FK_PROVINCE;

ALTER TABLE SYS_ORG 
DROP COLUMN PROVINCE_ID;

ALTER TABLE SYS_ORG 
ADD (PROVINCE_ID NUMBER(19) );

ALTER TABLE SYS_ORG
ADD CONSTRAINT ORG_FK_PROVINCE FOREIGN KEY
(
  PROVINCE_ID 
)
REFERENCES SYS_PROVINCE
(
  ID 
)
ENABLE;

ALTER TABLE SYS_ORG 
DROP COLUMN ORG_TYPE_ID;

ALTER TABLE SYS_ORG 
ADD (ORG_TYPE_ID NUMBER(19) );

ALTER TABLE SYS_ORG
ADD CONSTRAINT ORG_FK_TYPE FOREIGN KEY
(
  ORG_TYPE_ID 
)
REFERENCES SYS_ORG_TYPE
(
  ID 
)
ENABLE;

--3、初始化数据
delete from SYS_ORG_TYPE t;
Insert into SYS_ORG_TYPE (ID,CODE,NAME) values (1,'10','体彩机构');
Insert into SYS_ORG_TYPE (ID,CODE,NAME) values (2,'20','品牌机构');

delete from SYS_AUTHORITY t where t.ROLE_ID=3;
delete from SYS_ROLE_RESOURCE t where t.ROLE_ID=3;
delete from SYS_ROLE t where t.id=3;
Insert into SYS_ROLE (ID,NAME,DESCRIPTION,IS_SHOW) values (3,'省中心用户角色',null,1);

delete from SYS_ROLE_RESOURCE t where t.RESOURCE_ID in(38,39,40,41,42,43);
delete from SYS_RESOURCE t where t.id in(38,39,40,41,42,43);
Insert into SYS_RESOURCE (ID,NAME,IDENTIFIER,URL,PARENT_ID,PARENT_IDS,WEIGHT,HAS_CHILDREN,IS_SHOW,ICON,RESOURCE_TYPE_ID) values (38,'系统维护','maintain','/maintain',1,'0/1/',30,0,null,'fa fa-life-ring fa-fw',1);
Insert into SYS_RESOURCE (ID,NAME,IDENTIFIER,URL,PARENT_ID,PARENT_IDS,WEIGHT,HAS_CHILDREN,IS_SHOW,ICON,RESOURCE_TYPE_ID) values (39,'执行构造时段销量报表数据任务','generatePeriodSalesReportData','/maintain/excecutePeriodSalesReportJob',38,'0/1/38',0,0,null,null,2);
Insert into SYS_RESOURCE (ID,NAME,IDENTIFIER,URL,PARENT_ID,PARENT_IDS,WEIGHT,HAS_CHILDREN,IS_SHOW,ICON,RESOURCE_TYPE_ID) values (40,'系统设置','settings','/settings',1,'0/1/',10,1,null,'fa fa-cogs fa-fw',1);
Insert into SYS_RESOURCE (ID,NAME,IDENTIFIER,URL,PARENT_ID,PARENT_IDS,WEIGHT,HAS_CHILDREN,IS_SHOW,ICON,RESOURCE_TYPE_ID) values (41,'代理设置','agentSetting','/settings/agentSetting',40,'0/1/40',1,0,null,'fa fa-cog fa-fw',1);
Insert into SYS_RESOURCE (ID,NAME,IDENTIFIER,URL,PARENT_ID,PARENT_IDS,WEIGHT,HAS_CHILDREN,IS_SHOW,ICON,RESOURCE_TYPE_ID) values (42,'设置代理','setAgent','/settings/agentSetting/setAgent',41,'0/1/40/41',0,0,null,'fa fa-cog fa-fw',2);
Insert into SYS_RESOURCE (ID,NAME,IDENTIFIER,URL,PARENT_ID,PARENT_IDS,WEIGHT,HAS_CHILDREN,IS_SHOW,ICON,RESOURCE_TYPE_ID) values (43,'查询已设置代理api','queryAgentSetted','/api/settings/agentSetting/queryAgentSetted',41,'0/1/40/41',0,0,null,null,4);

Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (62,1,38);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (63,1,39);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (64,1,40);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (65,1,41);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (66,1,42);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (67,1,43);

Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (68,3,2);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (69,3,18);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (70,3,5);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (71,3,6);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (72,3,11);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (73,3,12);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (74,3,13);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (75,3,15);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (76,3,16);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (77,3,17);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (78,3,3);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (79,3,19);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (80,3,20);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (81,3,21);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (82,3,22);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (83,3,23);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (84,3,24);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (85,3,25);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (86,3,26);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (87,3,27);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (88,3,28);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (89,3,29);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (90,3,30);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (91,3,31);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (92,3,32);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (93,3,33);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (94,3,34);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (95,3,35);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (96,3,36);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (97,3,37);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (98,3,40);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (99,3,41);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (100,3,42);
Insert into SYS_ROLE_RESOURCE (ID,ROLE_ID,RESOURCE_ID) values (101,3,43);

--将省中心用户的角色改为省中心角色
update SYS_AUTHORITY t set t.ROLE_ID = 3 where t.ROLE_ID = 1 and t.USER_ID in (1036263,1036269,1036267,1036265);

--将市中心用户的角色改为普通角色
update SYS_AUTHORITY t set t.ROLE_ID = 2 where t.ROLE_ID = 1 and t.USER_ID in (1036233,1036231,1036227);

--给省中心用户增加普通用户角色
delete from SYS_AUTHORITY t where t.ROLE_ID = 2 and t.USER_ID in (1036263,1036269,1036267,1036265);
Insert into SYS_AUTHORITY (ID,ORGANIZATION_ID,ROLE_ID,USER_ID) values (AW_SEQUENCE.nextval,null,2,1036263);
Insert into SYS_AUTHORITY (ID,ORGANIZATION_ID,ROLE_ID,USER_ID) values (AW_SEQUENCE.nextval,null,2,1036269);
Insert into SYS_AUTHORITY (ID,ORGANIZATION_ID,ROLE_ID,USER_ID) values (AW_SEQUENCE.nextval,null,2,1036267);
Insert into SYS_AUTHORITY (ID,ORGANIZATION_ID,ROLE_ID,USER_ID) values (AW_SEQUENCE.nextval,null,2,1036265);

update SYS_ORG t set t.PROVINCE_ID = 16 where t.ID not in(1,2,3);

update SYS_AGENT t set t.PROVINCE_ID = 16 where t.PROVINCE_NO='37';

--给省中心用户增加超市机构
delete from SYS_USER_ORG t where t.USER_ID=1036263 and t.ORG_ID in(7,10,11,12,13,14);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,7,1036263);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,10,1036263);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,11,1036263);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,12,1036263);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,13,1036263);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,14,1036263);

delete from SYS_USER_ORG t where t.USER_ID=1036269 and t.ORG_ID in(7,10,11,12,13,14);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,7,1036269);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,10,1036269);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,11,1036269);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,12,1036269);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,13,1036269);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,14,1036269);

delete from SYS_USER_ORG t where t.USER_ID=1036267 and t.ORG_ID in(7,10,11,12,13,14);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,7,1036267);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,10,1036267);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,11,1036267);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,12,1036267);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,13,1036267);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,14,1036267);

delete from SYS_USER_ORG t where t.USER_ID=1036265 and t.ORG_ID in(7,10,11,12,13,14);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,7,1036265);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,10,1036265);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,11,1036265);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,12,1036265);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,13,1036265);
Insert into SYS_USER_ORG (ID,ORG_ID,USER_ID) values (AW_SEQUENCE.nextval,14,1036265);

delete from SYS_ORG_AGENT t where t.ORG_ID in (1,2,3,4,5,6);

--设置品牌机构和体彩机构类型
update SYS_ORG t set t.ORG_TYPE_ID = 2 where t.ID in (3,7,8,9,10,11,12,13,14);
update SYS_ORG t set t.ORG_TYPE_ID = 1 where t.ID in (2,4,5,6);

--增加竞彩游戏、排三、排五游戏
delete from SYS_GAME t where t.GAME_NO in ('898001','35','350133');
Insert into SYS_GAME (GAME_NO,GAME_NAME,GAME_SHORT_NAME,ID,PROVINCE_ID) values ('898001','竞彩玩法','竞彩玩法',11,1);
Insert into SYS_GAME (GAME_NO,GAME_NAME,GAME_SHORT_NAME,ID,PROVINCE_ID) values ('898001','竞彩玩法','竞彩玩法',12,16);
Insert into SYS_GAME (GAME_NO,GAME_NAME,GAME_SHORT_NAME,ID,PROVINCE_ID) values ('35','排列3','排列3',13,1);
Insert into SYS_GAME (GAME_NO,GAME_NAME,GAME_SHORT_NAME,ID,PROVINCE_ID) values ('35','排列3','排列3',14,16);
Insert into SYS_GAME (GAME_NO,GAME_NAME,GAME_SHORT_NAME,ID,PROVINCE_ID) values ('350133','排列5','排列5',15,1);
Insert into SYS_GAME (GAME_NO,GAME_NAME,GAME_SHORT_NAME,ID,PROVINCE_ID) values ('350133','排列5','排列5',16,16);

commit;