package cn.com.cslc.aw.reverseengineering.domain;
// Generated 2017-5-9 13:48:55 by Hibernate Tools 5.1.2.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RBaseReportId generated by hbm2java
 */
@Embeddable
public class RBaseReportId implements java.io.Serializable {

	private Date reportDate;
	private BigDecimal provinceCenterId;
	private BigDecimal terminalId;
	private BigDecimal shopId;
	private BigDecimal cityCenterId;

	public RBaseReportId() {
	}

	public RBaseReportId(Date reportDate, BigDecimal provinceCenterId, BigDecimal terminalId, BigDecimal shopId,
			BigDecimal cityCenterId) {
		this.reportDate = reportDate;
		this.provinceCenterId = provinceCenterId;
		this.terminalId = terminalId;
		this.shopId = shopId;
		this.cityCenterId = cityCenterId;
	}

	@Column(name = "REPORT_DATE", nullable = false, length = 7)
	public Date getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}

	@Column(name = "PROVINCE_CENTER_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getProvinceCenterId() {
		return this.provinceCenterId;
	}

	public void setProvinceCenterId(BigDecimal provinceCenterId) {
		this.provinceCenterId = provinceCenterId;
	}

	@Column(name = "TERMINAL_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTerminalId() {
		return this.terminalId;
	}

	public void setTerminalId(BigDecimal terminalId) {
		this.terminalId = terminalId;
	}

	@Column(name = "SHOP_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getShopId() {
		return this.shopId;
	}

	public void setShopId(BigDecimal shopId) {
		this.shopId = shopId;
	}

	@Column(name = "CITY_CENTER_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCityCenterId() {
		return this.cityCenterId;
	}

	public void setCityCenterId(BigDecimal cityCenterId) {
		this.cityCenterId = cityCenterId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RBaseReportId))
			return false;
		RBaseReportId castOther = (RBaseReportId) other;

		return ((this.getReportDate() == castOther.getReportDate()) || (this.getReportDate() != null
				&& castOther.getReportDate() != null && this.getReportDate().equals(castOther.getReportDate())))
				&& ((this.getProvinceCenterId() == castOther.getProvinceCenterId())
						|| (this.getProvinceCenterId() != null && castOther.getProvinceCenterId() != null
								&& this.getProvinceCenterId().equals(castOther.getProvinceCenterId())))
				&& ((this.getTerminalId() == castOther.getTerminalId()) || (this.getTerminalId() != null
						&& castOther.getTerminalId() != null && this.getTerminalId().equals(castOther.getTerminalId())))
				&& ((this.getShopId() == castOther.getShopId()) || (this.getShopId() != null
						&& castOther.getShopId() != null && this.getShopId().equals(castOther.getShopId())))
				&& ((this.getCityCenterId() == castOther.getCityCenterId())
						|| (this.getCityCenterId() != null && castOther.getCityCenterId() != null
								&& this.getCityCenterId().equals(castOther.getCityCenterId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getReportDate() == null ? 0 : this.getReportDate().hashCode());
		result = 37 * result + (getProvinceCenterId() == null ? 0 : this.getProvinceCenterId().hashCode());
		result = 37 * result + (getTerminalId() == null ? 0 : this.getTerminalId().hashCode());
		result = 37 * result + (getShopId() == null ? 0 : this.getShopId().hashCode());
		result = 37 * result + (getCityCenterId() == null ? 0 : this.getCityCenterId().hashCode());
		return result;
	}

}
