package cn.com.cslc.aw.reverseengineering.domain;
// Generated 2017-5-9 13:48:55 by Hibernate Tools 5.1.2.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RBaseReport generated by hbm2java
 */
@Entity
@Table(name = "R_BASE_REPORT", schema = "AW")
public class RBaseReport implements java.io.Serializable {

	private RBaseReportId id;
	private String terminalNo;
	private String shopNo;
	private BigDecimal gameId;
	private BigDecimal techSystemId;
	private BigDecimal channelTypeCode;
	private BigDecimal saleLotteryCnt;
	private BigDecimal saleStakeCnt;
	private BigDecimal saleAmount;
	private BigDecimal saleLotteryCntSettled;
	private BigDecimal saleStakeCntSettled;
	private BigDecimal saleAmountSettled;
	private BigDecimal saleLotteryCntMulti;
	private BigDecimal saleStakeCntMulti;
	private BigDecimal saleAmountMulti;
	private BigDecimal cancelLotteryCnt;
	private BigDecimal cancelStakeCnt;
	private BigDecimal cancelAmount;
	private BigDecimal paidLotteryCnt;
	private BigDecimal paidStakeCnt;
	private BigDecimal paidAmount;

	public RBaseReport() {
	}

	public RBaseReport(RBaseReportId id, BigDecimal gameId, BigDecimal techSystemId, BigDecimal channelTypeCode) {
		this.id = id;
		this.gameId = gameId;
		this.techSystemId = techSystemId;
		this.channelTypeCode = channelTypeCode;
	}

	public RBaseReport(RBaseReportId id, String terminalNo, String shopNo, BigDecimal gameId, BigDecimal techSystemId,
			BigDecimal channelTypeCode, BigDecimal saleLotteryCnt, BigDecimal saleStakeCnt, BigDecimal saleAmount,
			BigDecimal saleLotteryCntSettled, BigDecimal saleStakeCntSettled, BigDecimal saleAmountSettled,
			BigDecimal saleLotteryCntMulti, BigDecimal saleStakeCntMulti, BigDecimal saleAmountMulti,
			BigDecimal cancelLotteryCnt, BigDecimal cancelStakeCnt, BigDecimal cancelAmount, BigDecimal paidLotteryCnt,
			BigDecimal paidStakeCnt, BigDecimal paidAmount) {
		this.id = id;
		this.terminalNo = terminalNo;
		this.shopNo = shopNo;
		this.gameId = gameId;
		this.techSystemId = techSystemId;
		this.channelTypeCode = channelTypeCode;
		this.saleLotteryCnt = saleLotteryCnt;
		this.saleStakeCnt = saleStakeCnt;
		this.saleAmount = saleAmount;
		this.saleLotteryCntSettled = saleLotteryCntSettled;
		this.saleStakeCntSettled = saleStakeCntSettled;
		this.saleAmountSettled = saleAmountSettled;
		this.saleLotteryCntMulti = saleLotteryCntMulti;
		this.saleStakeCntMulti = saleStakeCntMulti;
		this.saleAmountMulti = saleAmountMulti;
		this.cancelLotteryCnt = cancelLotteryCnt;
		this.cancelStakeCnt = cancelStakeCnt;
		this.cancelAmount = cancelAmount;
		this.paidLotteryCnt = paidLotteryCnt;
		this.paidStakeCnt = paidStakeCnt;
		this.paidAmount = paidAmount;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "reportDate", column = @Column(name = "REPORT_DATE", nullable = false, length = 7)),
			@AttributeOverride(name = "provinceCenterId", column = @Column(name = "PROVINCE_CENTER_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "terminalId", column = @Column(name = "TERMINAL_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "shopId", column = @Column(name = "SHOP_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "cityCenterId", column = @Column(name = "CITY_CENTER_ID", nullable = false, precision = 22, scale = 0)) })
	public RBaseReportId getId() {
		return this.id;
	}

	public void setId(RBaseReportId id) {
		this.id = id;
	}

	@Column(name = "TERMINAL_NO", length = 16)
	public String getTerminalNo() {
		return this.terminalNo;
	}

	public void setTerminalNo(String terminalNo) {
		this.terminalNo = terminalNo;
	}

	@Column(name = "SHOP_NO", length = 10)
	public String getShopNo() {
		return this.shopNo;
	}

	public void setShopNo(String shopNo) {
		this.shopNo = shopNo;
	}

	@Column(name = "GAME_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getGameId() {
		return this.gameId;
	}

	public void setGameId(BigDecimal gameId) {
		this.gameId = gameId;
	}

	@Column(name = "TECH_SYSTEM_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTechSystemId() {
		return this.techSystemId;
	}

	public void setTechSystemId(BigDecimal techSystemId) {
		this.techSystemId = techSystemId;
	}

	@Column(name = "CHANNEL_TYPE_CODE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getChannelTypeCode() {
		return this.channelTypeCode;
	}

	public void setChannelTypeCode(BigDecimal channelTypeCode) {
		this.channelTypeCode = channelTypeCode;
	}

	@Column(name = "SALE_LOTTERY_CNT", precision = 22, scale = 0)
	public BigDecimal getSaleLotteryCnt() {
		return this.saleLotteryCnt;
	}

	public void setSaleLotteryCnt(BigDecimal saleLotteryCnt) {
		this.saleLotteryCnt = saleLotteryCnt;
	}

	@Column(name = "SALE_STAKE_CNT", precision = 22, scale = 0)
	public BigDecimal getSaleStakeCnt() {
		return this.saleStakeCnt;
	}

	public void setSaleStakeCnt(BigDecimal saleStakeCnt) {
		this.saleStakeCnt = saleStakeCnt;
	}

	@Column(name = "SALE_AMOUNT", precision = 22, scale = 0)
	public BigDecimal getSaleAmount() {
		return this.saleAmount;
	}

	public void setSaleAmount(BigDecimal saleAmount) {
		this.saleAmount = saleAmount;
	}

	@Column(name = "SALE_LOTTERY_CNT_SETTLED", precision = 22, scale = 0)
	public BigDecimal getSaleLotteryCntSettled() {
		return this.saleLotteryCntSettled;
	}

	public void setSaleLotteryCntSettled(BigDecimal saleLotteryCntSettled) {
		this.saleLotteryCntSettled = saleLotteryCntSettled;
	}

	@Column(name = "SALE_STAKE_CNT_SETTLED", precision = 22, scale = 0)
	public BigDecimal getSaleStakeCntSettled() {
		return this.saleStakeCntSettled;
	}

	public void setSaleStakeCntSettled(BigDecimal saleStakeCntSettled) {
		this.saleStakeCntSettled = saleStakeCntSettled;
	}

	@Column(name = "SALE_AMOUNT_SETTLED", precision = 22, scale = 0)
	public BigDecimal getSaleAmountSettled() {
		return this.saleAmountSettled;
	}

	public void setSaleAmountSettled(BigDecimal saleAmountSettled) {
		this.saleAmountSettled = saleAmountSettled;
	}

	@Column(name = "SALE_LOTTERY_CNT_MULTI", precision = 22, scale = 0)
	public BigDecimal getSaleLotteryCntMulti() {
		return this.saleLotteryCntMulti;
	}

	public void setSaleLotteryCntMulti(BigDecimal saleLotteryCntMulti) {
		this.saleLotteryCntMulti = saleLotteryCntMulti;
	}

	@Column(name = "SALE_STAKE_CNT_MULTI", precision = 22, scale = 0)
	public BigDecimal getSaleStakeCntMulti() {
		return this.saleStakeCntMulti;
	}

	public void setSaleStakeCntMulti(BigDecimal saleStakeCntMulti) {
		this.saleStakeCntMulti = saleStakeCntMulti;
	}

	@Column(name = "SALE_AMOUNT_MULTI", precision = 22, scale = 0)
	public BigDecimal getSaleAmountMulti() {
		return this.saleAmountMulti;
	}

	public void setSaleAmountMulti(BigDecimal saleAmountMulti) {
		this.saleAmountMulti = saleAmountMulti;
	}

	@Column(name = "CANCEL_LOTTERY_CNT", precision = 22, scale = 0)
	public BigDecimal getCancelLotteryCnt() {
		return this.cancelLotteryCnt;
	}

	public void setCancelLotteryCnt(BigDecimal cancelLotteryCnt) {
		this.cancelLotteryCnt = cancelLotteryCnt;
	}

	@Column(name = "CANCEL_STAKE_CNT", precision = 22, scale = 0)
	public BigDecimal getCancelStakeCnt() {
		return this.cancelStakeCnt;
	}

	public void setCancelStakeCnt(BigDecimal cancelStakeCnt) {
		this.cancelStakeCnt = cancelStakeCnt;
	}

	@Column(name = "CANCEL_AMOUNT", precision = 22, scale = 0)
	public BigDecimal getCancelAmount() {
		return this.cancelAmount;
	}

	public void setCancelAmount(BigDecimal cancelAmount) {
		this.cancelAmount = cancelAmount;
	}

	@Column(name = "PAID_LOTTERY_CNT", precision = 22, scale = 0)
	public BigDecimal getPaidLotteryCnt() {
		return this.paidLotteryCnt;
	}

	public void setPaidLotteryCnt(BigDecimal paidLotteryCnt) {
		this.paidLotteryCnt = paidLotteryCnt;
	}

	@Column(name = "PAID_STAKE_CNT", precision = 22, scale = 0)
	public BigDecimal getPaidStakeCnt() {
		return this.paidStakeCnt;
	}

	public void setPaidStakeCnt(BigDecimal paidStakeCnt) {
		this.paidStakeCnt = paidStakeCnt;
	}

	@Column(name = "PAID_AMOUNT", precision = 22, scale = 0)
	public BigDecimal getPaidAmount() {
		return this.paidAmount;
	}

	public void setPaidAmount(BigDecimal paidAmount) {
		this.paidAmount = paidAmount;
	}

}
