package cn.com.cslc.aw.reverseengineering.domain;
// Generated 2017-5-9 13:48:55 by Hibernate Tools 5.1.2.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SysAuthority generated by hbm2java
 */
@Entity
@Table(name = "SYS_AUTHORITY", schema = "AW")
public class SysAuthority implements java.io.Serializable {

	private BigDecimal id;
	private SysRole sysRole;
	private SysUser sysUser;
	private BigDecimal organizationId;

	public SysAuthority() {
	}

	public SysAuthority(BigDecimal id) {
		this.id = id;
	}

	public SysAuthority(BigDecimal id, SysRole sysRole, SysUser sysUser, BigDecimal organizationId) {
		this.id = id;
		this.sysRole = sysRole;
		this.sysUser = sysUser;
		this.organizationId = organizationId;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLE_ID")
	public SysRole getSysRole() {
		return this.sysRole;
	}

	public void setSysRole(SysRole sysRole) {
		this.sysRole = sysRole;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID")
	public SysUser getSysUser() {
		return this.sysUser;
	}

	public void setSysUser(SysUser sysUser) {
		this.sysUser = sysUser;
	}

	@Column(name = "ORGANIZATION_ID", scale = 0)
	public BigDecimal getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(BigDecimal organizationId) {
		this.organizationId = organizationId;
	}

}
