package cn.com.cslc.aw.reverseengineering.domain;
// Generated 2017-5-9 13:48:55 by Hibernate Tools 5.1.2.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SysCity generated by hbm2java
 */
@Entity
@Table(name = "SYS_CITY", schema = "AW")
public class SysCity implements java.io.Serializable {

	private BigDecimal id;
	private SysProvince sysProvince;
	private String cityNo;
	private String cityName;
	private String cityShortName;
	private String cityFullName;
	private Long capitalFlag;
	private Long sortId;
	private Serializable statusChangeTime;
	private Long statusCode;
	private Long delFlag;
	private Serializable delTime;
	private Set<SysUser> sysUsers = new HashSet<SysUser>(0);

	public SysCity() {
	}

	public SysCity(BigDecimal id) {
		this.id = id;
	}

	public SysCity(BigDecimal id, SysProvince sysProvince, String cityNo, String cityName, String cityShortName,
			String cityFullName, Long capitalFlag, Long sortId, Serializable statusChangeTime, Long statusCode,
			Long delFlag, Serializable delTime, Set<SysUser> sysUsers) {
		this.id = id;
		this.sysProvince = sysProvince;
		this.cityNo = cityNo;
		this.cityName = cityName;
		this.cityShortName = cityShortName;
		this.cityFullName = cityFullName;
		this.capitalFlag = capitalFlag;
		this.sortId = sortId;
		this.statusChangeTime = statusChangeTime;
		this.statusCode = statusCode;
		this.delFlag = delFlag;
		this.delTime = delTime;
		this.sysUsers = sysUsers;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROVINCE_ID")
	public SysProvince getSysProvince() {
		return this.sysProvince;
	}

	public void setSysProvince(SysProvince sysProvince) {
		this.sysProvince = sysProvince;
	}

	@Column(name = "CITY_NO", length = 24)
	public String getCityNo() {
		return this.cityNo;
	}

	public void setCityNo(String cityNo) {
		this.cityNo = cityNo;
	}

	@Column(name = "CITY_NAME", length = 120)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@Column(name = "CITY_SHORT_NAME", length = 120)
	public String getCityShortName() {
		return this.cityShortName;
	}

	public void setCityShortName(String cityShortName) {
		this.cityShortName = cityShortName;
	}

	@Column(name = "CITY_FULL_NAME", length = 240)
	public String getCityFullName() {
		return this.cityFullName;
	}

	public void setCityFullName(String cityFullName) {
		this.cityFullName = cityFullName;
	}

	@Column(name = "CAPITAL_FLAG", precision = 10, scale = 0)
	public Long getCapitalFlag() {
		return this.capitalFlag;
	}

	public void setCapitalFlag(Long capitalFlag) {
		this.capitalFlag = capitalFlag;
	}

	@Column(name = "SORT_ID", precision = 10, scale = 0)
	public Long getSortId() {
		return this.sortId;
	}

	public void setSortId(Long sortId) {
		this.sortId = sortId;
	}

	@Column(name = "STATUS_CHANGE_TIME")
	public Serializable getStatusChangeTime() {
		return this.statusChangeTime;
	}

	public void setStatusChangeTime(Serializable statusChangeTime) {
		this.statusChangeTime = statusChangeTime;
	}

	@Column(name = "STATUS_CODE", precision = 10, scale = 0)
	public Long getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(Long statusCode) {
		this.statusCode = statusCode;
	}

	@Column(name = "DEL_FLAG", precision = 10, scale = 0)
	public Long getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(Long delFlag) {
		this.delFlag = delFlag;
	}

	@Column(name = "DEL_TIME")
	public Serializable getDelTime() {
		return this.delTime;
	}

	public void setDelTime(Serializable delTime) {
		this.delTime = delTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysCredentialType")
	public Set<SysUser> getSysUsers() {
		return this.sysUsers;
	}

	public void setSysUsers(Set<SysUser> sysUsers) {
		this.sysUsers = sysUsers;
	}

}
