package cn.com.cslc.aw.reverseengineering.domain;
// Generated 2017-5-9 13:48:55 by Hibernate Tools 5.1.2.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SysOrganization generated by hbm2java
 */
@Entity
@Table(name = "SYS_ORGANIZATION", schema = "AW")
public class SysOrganization implements java.io.Serializable {

	private BigDecimal id;
	private String name;
	private BigDecimal parentId;
	private String parentIds;
	private Short isShow;
	private Short hasChildren;
	private Long weight;
	private Set<SysUserOrganization> sysUserOrganizations = new HashSet<SysUserOrganization>(0);

	public SysOrganization() {
	}

	public SysOrganization(BigDecimal id) {
		this.id = id;
	}

	public SysOrganization(BigDecimal id, String name, BigDecimal parentId, String parentIds, Short isShow,
			Short hasChildren, Long weight, Set<SysUserOrganization> sysUserOrganizations) {
		this.id = id;
		this.name = name;
		this.parentId = parentId;
		this.parentIds = parentIds;
		this.isShow = isShow;
		this.hasChildren = hasChildren;
		this.weight = weight;
		this.sysUserOrganizations = sysUserOrganizations;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 400)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PARENT_ID", scale = 0)
	public BigDecimal getParentId() {
		return this.parentId;
	}

	public void setParentId(BigDecimal parentId) {
		this.parentId = parentId;
	}

	@Column(name = "PARENT_IDS", length = 800)
	public String getParentIds() {
		return this.parentIds;
	}

	public void setParentIds(String parentIds) {
		this.parentIds = parentIds;
	}

	@Column(name = "IS_SHOW", precision = 3, scale = 0)
	public Short getIsShow() {
		return this.isShow;
	}

	public void setIsShow(Short isShow) {
		this.isShow = isShow;
	}

	@Column(name = "HAS_CHILDREN", precision = 3, scale = 0)
	public Short getHasChildren() {
		return this.hasChildren;
	}

	public void setHasChildren(Short hasChildren) {
		this.hasChildren = hasChildren;
	}

	@Column(name = "WEIGHT", precision = 10, scale = 0)
	public Long getWeight() {
		return this.weight;
	}

	public void setWeight(Long weight) {
		this.weight = weight;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysOrganization")
	public Set<SysUserOrganization> getSysUserOrganizations() {
		return this.sysUserOrganizations;
	}

	public void setSysUserOrganizations(Set<SysUserOrganization> sysUserOrganizations) {
		this.sysUserOrganizations = sysUserOrganizations;
	}

}
