package cn.com.cslc.aw.reverseengineering.domain;
// Generated 2017-4-12 13:58:55 by Hibernate Tools 5.1.2.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysPermission generated by hbm2java
 */
@Entity
@Table(name = "sys_permission")
public class SysPermission implements java.io.Serializable {

	private long id;
	private String name;
	private Integer identifier;
	private String description;
	private Byte isShow;

	public SysPermission() {
	}

	public SysPermission(long id) {
		this.id = id;
	}

	public SysPermission(long id, String name, Integer identifier, String description, Byte isShow) {
		this.id = id;
		this.name = name;
		this.identifier = identifier;
		this.description = description;
		this.isShow = isShow;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "identifier")
	public Integer getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(Integer identifier) {
		this.identifier = identifier;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "is_show")
	public Byte getIsShow() {
		return this.isShow;
	}

	public void setIsShow(Byte isShow) {
		this.isShow = isShow;
	}

}
