package cn.com.cslc.aw.reverseengineering.domain;
// Generated 2017-5-9 13:48:55 by Hibernate Tools 5.1.2.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SysProvince generated by hbm2java
 */
@Entity
@Table(name = "SYS_PROVINCE", schema = "AW")
public class SysProvince implements java.io.Serializable {

	private BigDecimal id;
	private String provinceNo;
	private String provinceName;
	private String provinceFullName;
	private String provinceShortName;
	private String alphabeticCode;
	private Long countryId;
	private Long delFlag;
	private Serializable delTime;
	private Long sortId;
	private Serializable statusChangeTime;
	private String statusCode;
	private Set<SysCity> sysCities = new HashSet<SysCity>(0);
	private Set<SysUser> sysUsers = new HashSet<SysUser>(0);

	public SysProvince() {
	}

	public SysProvince(BigDecimal id) {
		this.id = id;
	}

	public SysProvince(BigDecimal id, String provinceNo, String provinceName, String provinceFullName,
			String provinceShortName, String alphabeticCode, Long countryId, Long delFlag, Serializable delTime,
			Long sortId, Serializable statusChangeTime, String statusCode, Set<SysCity> sysCities,
			Set<SysUser> sysUsers) {
		this.id = id;
		this.provinceNo = provinceNo;
		this.provinceName = provinceName;
		this.provinceFullName = provinceFullName;
		this.provinceShortName = provinceShortName;
		this.alphabeticCode = alphabeticCode;
		this.countryId = countryId;
		this.delFlag = delFlag;
		this.delTime = delTime;
		this.sortId = sortId;
		this.statusChangeTime = statusChangeTime;
		this.statusCode = statusCode;
		this.sysCities = sysCities;
		this.sysUsers = sysUsers;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "PROVINCE_NO", length = 24)
	public String getProvinceNo() {
		return this.provinceNo;
	}

	public void setProvinceNo(String provinceNo) {
		this.provinceNo = provinceNo;
	}

	@Column(name = "PROVINCE_NAME", length = 120)
	public String getProvinceName() {
		return this.provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	@Column(name = "PROVINCE_FULL_NAME", length = 240)
	public String getProvinceFullName() {
		return this.provinceFullName;
	}

	public void setProvinceFullName(String provinceFullName) {
		this.provinceFullName = provinceFullName;
	}

	@Column(name = "PROVINCE_SHORT_NAME", length = 120)
	public String getProvinceShortName() {
		return this.provinceShortName;
	}

	public void setProvinceShortName(String provinceShortName) {
		this.provinceShortName = provinceShortName;
	}

	@Column(name = "ALPHABETIC_CODE", length = 120)
	public String getAlphabeticCode() {
		return this.alphabeticCode;
	}

	public void setAlphabeticCode(String alphabeticCode) {
		this.alphabeticCode = alphabeticCode;
	}

	@Column(name = "COUNTRY_ID", precision = 10, scale = 0)
	public Long getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Long countryId) {
		this.countryId = countryId;
	}

	@Column(name = "DEL_FLAG", precision = 10, scale = 0)
	public Long getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(Long delFlag) {
		this.delFlag = delFlag;
	}

	@Column(name = "DEL_TIME")
	public Serializable getDelTime() {
		return this.delTime;
	}

	public void setDelTime(Serializable delTime) {
		this.delTime = delTime;
	}

	@Column(name = "SORT_ID", precision = 10, scale = 0)
	public Long getSortId() {
		return this.sortId;
	}

	public void setSortId(Long sortId) {
		this.sortId = sortId;
	}

	@Column(name = "STATUS_CHANGE_TIME")
	public Serializable getStatusChangeTime() {
		return this.statusChangeTime;
	}

	public void setStatusChangeTime(Serializable statusChangeTime) {
		this.statusChangeTime = statusChangeTime;
	}

	@Column(name = "STATUS_CODE", length = 180)
	public String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysProvince")
	public Set<SysCity> getSysCities() {
		return this.sysCities;
	}

	public void setSysCities(Set<SysCity> sysCities) {
		this.sysCities = sysCities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysProvince")
	public Set<SysUser> getSysUsers() {
		return this.sysUsers;
	}

	public void setSysUsers(Set<SysUser> sysUsers) {
		this.sysUsers = sysUsers;
	}

}
