package cn.com.cslc.aw.reverseengineering.domain;
// Generated 2017-5-9 13:48:55 by Hibernate Tools 5.1.2.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SysResource generated by hbm2java
 */
@Entity
@Table(name = "SYS_RESOURCE", schema = "AW")
public class SysResource implements java.io.Serializable {

	private BigDecimal id;
	private SysResourceType sysResourceType;
	private String name;
	private String identifier;
	private String url;
	private BigDecimal parentId;
	private String parentIds;
	private Long weight;
	private Short hasChildren;
	private Short isShow;
	private String icon;
	private Set<SysRoleResource> sysRoleResources = new HashSet<SysRoleResource>(0);

	public SysResource() {
	}

	public SysResource(BigDecimal id, String identifier) {
		this.id = id;
		this.identifier = identifier;
	}

	public SysResource(BigDecimal id, SysResourceType sysResourceType, String name, String identifier, String url,
			BigDecimal parentId, String parentIds, Long weight, Short hasChildren, Short isShow, String icon,
			Set<SysRoleResource> sysRoleResources) {
		this.id = id;
		this.sysResourceType = sysResourceType;
		this.name = name;
		this.identifier = identifier;
		this.url = url;
		this.parentId = parentId;
		this.parentIds = parentIds;
		this.weight = weight;
		this.hasChildren = hasChildren;
		this.isShow = isShow;
		this.icon = icon;
		this.sysRoleResources = sysRoleResources;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESOURCE_TYPE_ID")
	public SysResourceType getSysResourceType() {
		return this.sysResourceType;
	}

	public void setSysResourceType(SysResourceType sysResourceType) {
		this.sysResourceType = sysResourceType;
	}

	@Column(name = "NAME", length = 400)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "IDENTIFIER", nullable = false, length = 400)
	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	@Column(name = "URL", length = 800)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "PARENT_ID", scale = 0)
	public BigDecimal getParentId() {
		return this.parentId;
	}

	public void setParentId(BigDecimal parentId) {
		this.parentId = parentId;
	}

	@Column(name = "PARENT_IDS", length = 800)
	public String getParentIds() {
		return this.parentIds;
	}

	public void setParentIds(String parentIds) {
		this.parentIds = parentIds;
	}

	@Column(name = "WEIGHT", precision = 10, scale = 0)
	public Long getWeight() {
		return this.weight;
	}

	public void setWeight(Long weight) {
		this.weight = weight;
	}

	@Column(name = "HAS_CHILDREN", precision = 3, scale = 0)
	public Short getHasChildren() {
		return this.hasChildren;
	}

	public void setHasChildren(Short hasChildren) {
		this.hasChildren = hasChildren;
	}

	@Column(name = "IS_SHOW", precision = 3, scale = 0)
	public Short getIsShow() {
		return this.isShow;
	}

	public void setIsShow(Short isShow) {
		this.isShow = isShow;
	}

	@Column(name = "ICON", length = 800)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysResource")
	public Set<SysRoleResource> getSysRoleResources() {
		return this.sysRoleResources;
	}

	public void setSysRoleResources(Set<SysRoleResource> sysRoleResources) {
		this.sysRoleResources = sysRoleResources;
	}

}
