package cn.com.cslc.aw.reverseengineering.domain;
// Generated 2017-4-12 13:58:55 by Hibernate Tools 5.1.2.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SysRoleResourcePermission generated by hbm2java
 */
@Entity
@Table(name = "sys_role_resource_permission")
public class SysRoleResourcePermission implements java.io.Serializable {

	private long id;
	private SysResource sysResource;
	private SysRole sysRole;
	private Integer permissions;

	public SysRoleResourcePermission() {
	}

	public SysRoleResourcePermission(long id) {
		this.id = id;
	}

	public SysRoleResourcePermission(long id, SysResource sysResource, SysRole sysRole, Integer permissions) {
		this.id = id;
		this.sysResource = sysResource;
		this.sysRole = sysRole;
		this.permissions = permissions;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resource_id")
	public SysResource getSysResource() {
		return this.sysResource;
	}

	public void setSysResource(SysResource sysResource) {
		this.sysResource = sysResource;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id")
	public SysRole getSysRole() {
		return this.sysRole;
	}

	public void setSysRole(SysRole sysRole) {
		this.sysRole = sysRole;
	}

	@Column(name = "permissions")
	public Integer getPermissions() {
		return this.permissions;
	}

	public void setPermissions(Integer permissions) {
		this.permissions = permissions;
	}

}
