package cn.com.cslc.aw.reverseengineering.domain;
// Generated 2017-5-9 13:48:55 by Hibernate Tools 5.1.2.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SysRole generated by hbm2java
 */
@Entity
@Table(name = "SYS_ROLE", schema = "AW")
public class SysRole implements java.io.Serializable {

	private BigDecimal id;
	private String name;
	private String description;
	private Short isShow;
	private Set<SysAuthority> sysAuthorities = new HashSet<SysAuthority>(0);
	private Set<SysRoleResource> sysRoleResources = new HashSet<SysRoleResource>(0);

	public SysRole() {
	}

	public SysRole(BigDecimal id) {
		this.id = id;
	}

	public SysRole(BigDecimal id, String name, String description, Short isShow, Set<SysAuthority> sysAuthorities,
			Set<SysRoleResource> sysRoleResources) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.isShow = isShow;
		this.sysAuthorities = sysAuthorities;
		this.sysRoleResources = sysRoleResources;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 400)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 800)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "IS_SHOW", precision = 3, scale = 0)
	public Short getIsShow() {
		return this.isShow;
	}

	public void setIsShow(Short isShow) {
		this.isShow = isShow;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysRole")
	public Set<SysAuthority> getSysAuthorities() {
		return this.sysAuthorities;
	}

	public void setSysAuthorities(Set<SysAuthority> sysAuthorities) {
		this.sysAuthorities = sysAuthorities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysRole")
	public Set<SysRoleResource> getSysRoleResources() {
		return this.sysRoleResources;
	}

	public void setSysRoleResources(Set<SysRoleResource> sysRoleResources) {
		this.sysRoleResources = sysRoleResources;
	}

}
