package cn.com.cslc.aw.reverseengineering.domain;
// Generated 2017-5-9 13:48:55 by Hibernate Tools 5.1.2.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SysUser generated by hbm2java
 */
@Entity
@Table(name = "SYS_USER", schema = "AW")
public class SysUser implements java.io.Serializable {

	private BigDecimal id;
	private SysCity sysCredentialType;
	private SysProvince sysProvince;
	private SysUserState sysUserState;
	private String userName;
	private String description;
	private String mobilePhoneNumber;
	private String password;
	private Serializable createDate;
	private String userFullName;
	private BigDecimal cityId;
	private BigDecimal umpUserId;
	private String email;
	private String credentialNo;
	private Serializable lastOperDate;
	private Set<SysUserOrganization> sysUserOrganizations = new HashSet<SysUserOrganization>(0);
	private Set<SysAuthority> sysAuthorities = new HashSet<SysAuthority>(0);

	public SysUser() {
	}

	public SysUser(BigDecimal id) {
		this.id = id;
	}

	public SysUser(BigDecimal id, SysCity sysCredentialType, SysProvince sysProvince, SysUserState sysUserState,
			String userName, String description, String mobilePhoneNumber, String password, Serializable createDate,
			String userFullName, BigDecimal cityId, BigDecimal umpUserId, String email, String credentialNo,
			Serializable lastOperDate, Set<SysUserOrganization> sysUserOrganizations,
			Set<SysAuthority> sysAuthorities) {
		this.id = id;
		this.sysCredentialType = sysCredentialType;
		this.sysProvince = sysProvince;
		this.sysUserState = sysUserState;
		this.userName = userName;
		this.description = description;
		this.mobilePhoneNumber = mobilePhoneNumber;
		this.password = password;
		this.createDate = createDate;
		this.userFullName = userFullName;
		this.cityId = cityId;
		this.umpUserId = umpUserId;
		this.email = email;
		this.credentialNo = credentialNo;
		this.lastOperDate = lastOperDate;
		this.sysUserOrganizations = sysUserOrganizations;
		this.sysAuthorities = sysAuthorities;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREDENTIAL_TYPE_ID")
	public SysCity getSysCredentialType() {
		return this.sysCredentialType;
	}

	public void setSysCredentialType(SysCity sysCredentialType) {
		this.sysCredentialType = sysCredentialType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROVINCE_ID")
	public SysProvince getSysProvince() {
		return this.sysProvince;
	}

	public void setSysProvince(SysProvince sysProvince) {
		this.sysProvince = sysProvince;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_STATE_ID")
	public SysUserState getSysUserState() {
		return this.sysUserState;
	}

	public void setSysUserState(SysUserState sysUserState) {
		this.sysUserState = sysUserState;
	}

	@Column(name = "USER_NAME", length = 400)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "DESCRIPTION", length = 800)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "MOBILE_PHONE_NUMBER", length = 80)
	public String getMobilePhoneNumber() {
		return this.mobilePhoneNumber;
	}

	public void setMobilePhoneNumber(String mobilePhoneNumber) {
		this.mobilePhoneNumber = mobilePhoneNumber;
	}

	@Column(name = "PASSWORD", length = 400)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "CREATE_DATE")
	public Serializable getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Serializable createDate) {
		this.createDate = createDate;
	}

	@Column(name = "USER_FULL_NAME", length = 400)
	public String getUserFullName() {
		return this.userFullName;
	}

	public void setUserFullName(String userFullName) {
		this.userFullName = userFullName;
	}

	@Column(name = "CITY_ID", scale = 0)
	public BigDecimal getCityId() {
		return this.cityId;
	}

	public void setCityId(BigDecimal cityId) {
		this.cityId = cityId;
	}

	@Column(name = "UMP_USER_ID", scale = 0)
	public BigDecimal getUmpUserId() {
		return this.umpUserId;
	}

	public void setUmpUserId(BigDecimal umpUserId) {
		this.umpUserId = umpUserId;
	}

	@Column(name = "EMAIL", length = 400)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "CREDENTIAL_NO", length = 200)
	public String getCredentialNo() {
		return this.credentialNo;
	}

	public void setCredentialNo(String credentialNo) {
		this.credentialNo = credentialNo;
	}

	@Column(name = "LAST_OPER_DATE")
	public Serializable getLastOperDate() {
		return this.lastOperDate;
	}

	public void setLastOperDate(Serializable lastOperDate) {
		this.lastOperDate = lastOperDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysUser")
	public Set<SysUserOrganization> getSysUserOrganizations() {
		return this.sysUserOrganizations;
	}

	public void setSysUserOrganizations(Set<SysUserOrganization> sysUserOrganizations) {
		this.sysUserOrganizations = sysUserOrganizations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysUser")
	public Set<SysAuthority> getSysAuthorities() {
		return this.sysAuthorities;
	}

	public void setSysAuthorities(Set<SysAuthority> sysAuthorities) {
		this.sysAuthorities = sysAuthorities;
	}

}
