package cn.com.cslc.aw.reverseengineering.domain;
// Generated 2017-5-9 13:48:55 by Hibernate Tools 5.1.2.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SysUserOrganization generated by hbm2java
 */
@Entity
@Table(name = "SYS_USER_ORGANIZATION", schema = "AW")
public class SysUserOrganization implements java.io.Serializable {

	private BigDecimal id;
	private SysOrganization sysOrganization;
	private SysUser sysUser;

	public SysUserOrganization() {
	}

	public SysUserOrganization(BigDecimal id) {
		this.id = id;
	}

	public SysUserOrganization(BigDecimal id, SysOrganization sysOrganization, SysUser sysUser) {
		this.id = id;
		this.sysOrganization = sysOrganization;
		this.sysUser = sysUser;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORGANIZATION_ID")
	public SysOrganization getSysOrganization() {
		return this.sysOrganization;
	}

	public void setSysOrganization(SysOrganization sysOrganization) {
		this.sysOrganization = sysOrganization;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID")
	public SysUser getSysUser() {
		return this.sysUser;
	}

	public void setSysUser(SysUser sysUser) {
		this.sysUser = sysUser;
	}

}
