package cn.com.cslc.aw.ws.client.generate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2017-07-28T15:16:22.998+08:00
 * Generated source version: 2.4.3
 * 
 */
@WebService(targetNamespace = "http://www.cslc.com.cn/aw/ws", name = "AwPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AwPort {

    @WebMethod(operationName = "SynchronizeUser")
    @WebResult(name = "SynchronizeUserResponse", targetNamespace = "http://www.cslc.com.cn/aw/ws", partName = "SynchronizeUserResponse")
    public SynchronizeUserResponse synchronizeUser(
        @WebParam(partName = "SynchronizeUserRequest", name = "SynchronizeUserRequest", targetNamespace = "http://www.cslc.com.cn/aw/ws")
        SynchronizeUserRequest synchronizeUserRequest
    );
}
