
package cn.com.cslc.aw.ws.client.generate;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2017-07-28T15:16:22.940+08:00
 * Generated source version: 2.4.3
 * 
 */
public final class AwPort_AwPortSoap11_Client {

    private static final QName SERVICE_NAME = new QName("http://www.cslc.com.cn/aw/ws", "AwPortService");

    private AwPort_AwPortSoap11_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AwPortService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AwPortService ss = new AwPortService(wsdlURL, SERVICE_NAME);
        AwPort port = ss.getAwPortSoap11();  
        
        {
        System.out.println("Invoking synchronizeUser...");
        cn.com.cslc.aw.ws.client.generate.SynchronizeUserRequest _synchronizeUser_synchronizeUserRequest = null;
        cn.com.cslc.aw.ws.client.generate.SynchronizeUserResponse _synchronizeUser__return = port.synchronizeUser(_synchronizeUser_synchronizeUserRequest);
        System.out.println("synchronizeUser.result=" + _synchronizeUser__return);


        }

        System.exit(0);
    }

}
