package cn.com.cslc.aw.core.common.domain;
// Generated 2017-4-10 14:10:27 by Hibernate Tools 5.1.2.Final

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SysAuthority generated by hbm2java
 */
@Entity
@Table(name = "sys_authority")
public class SysAuthority extends BaseEntity {

	private SysRole sysRole;
	private SysUser sysUser;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id")
	public SysRole getSysRole() {
		return this.sysRole;
	}

	public void setSysRole(SysRole sysRole) {
		this.sysRole = sysRole;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public SysUser getSysUser() {
		return this.sysUser;
	}

	public void setSysUser(SysUser sysUser) {
		this.sysUser = sysUser;
	}

}
