package cn.com.cslc.aw.core.common.domain;
// Generated 2017-3-29 13:36:52 by Hibernate Tools 5.1.2.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SysRole generated by hbm2java
 */
@Entity
@Table(name = "sys_role")
public class SysRole extends BaseEntity {

	private String name;
	private String description;
	private Byte isShow;
	private Set<SysRoleResource> sysRoleResource = new HashSet<SysRoleResource>(0);

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "is_show")
	public Byte getIsShow() {
		return this.isShow;
	}

	public void setIsShow(Byte isShow) {
		this.isShow = isShow;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysRole")
	public Set<SysRoleResource> getSysRoleResource() {
		return this.sysRoleResource;
	}

	public void setSysRoleResource(Set<SysRoleResource> sysRoleResource) {
		this.sysRoleResource = sysRoleResource;
	}

}
