package cn.com.cslc.aw.core.common.domain;
// Generated 2017-3-29 13:36:52 by Hibernate Tools 5.1.2.Final

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SysRoleResource generated by hbm2java
 */
@Entity
@Table(name = "sys_role_resource")
public class SysRoleResource extends BaseEntity {

	private SysResource sysResource;
	private SysRole sysRole;

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "resource_id")
	public SysResource getSysResource() {
		return this.sysResource;
	}

	public void setSysResource(SysResource sysResource) {
		this.sysResource = sysResource;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id")
	public SysRole getSysRole() {
		return this.sysRole;
	}

	public void setSysRole(SysRole sysRole) {
		this.sysRole = sysRole;
	}

}
