package cn.com.cslc.aw.core.common.domain;
// Generated 2017-8-14 15:23:58 by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysWsMessage generated by hbm2java
 */
@Entity
@Table(name = "SYS_WS_MESSAGE", schema = "TIGER")
public class SysWsMessage  extends BaseEntity {
	
	private String serialNumber;
	private String source;
	private Date requestTimestamp;
	private String requestMessage;
	private String responseMessage;
	private Date responseTimestamp;

	@Column(name = "SERIAL_NUMBER", length = 50)
	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	@Column(name = "SOURCE", length = 20)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REQUEST_TIMESTAMP", length = 19)
	public Date getRequestTimestamp() {
		return this.requestTimestamp;
	}

	public void setRequestTimestamp(Date requestTimestamp) {
		this.requestTimestamp = requestTimestamp;
	}

	@Column(name = "REQUEST_MESSAGE", length = 2000)
	public String getRequestMessage() {
		return this.requestMessage;
	}

	public void setRequestMessage(String requestMessage) {
		this.requestMessage = requestMessage;
	}

	@Column(name = "RESPONSE_MESSAGE", length = 2000)
	public String getResponseMessage() {
		return this.responseMessage;
	}

	public void setResponseMessage(String responseMessage) {
		this.responseMessage = responseMessage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RESPONSE_TIMESTAMP", length = 19)
	public Date getResponseTimestamp() {
		return this.responseTimestamp;
	}

	public void setResponseTimestamp(Date responseTimestamp) {
		this.responseTimestamp = responseTimestamp;
	}

}
