package cn.com.cslc.aw.reports.periodsales.domain;
// Generated 2017-9-1 4:24:13 by Hibernate Tools 5.1.2.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import cn.com.cslc.aw.core.common.domain.BaseEntity;

/**
 * SysPeriodSalesReportTemp generated by hbm2java
 */
@Entity
@Table(name = "SYS_PERIOD_SALES_REPORT_TEMP")
public class SysPeriodSalesReportTemp  extends BaseEntity {

	private Date reportDate;
	private BigDecimal terminalId;
	private BigDecimal shopId;
	private String shopNo;
	private BigDecimal agentId;
	private BigDecimal cityId;
	private BigDecimal provinceId;
	private String terminalNo;
	private String agentNo;
	private String cityNo;
	private String provinceNo;

	@Temporal(TemporalType.DATE)
	@Column(name = "REPORT_DATE", length = 7)
	public Date getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}

	@Column(name = "TERMINAL_ID", precision = 22, scale = 0)
	public BigDecimal getTerminalId() {
		return this.terminalId;
	}

	public void setTerminalId(BigDecimal terminalId) {
		this.terminalId = terminalId;
	}

	@Column(name = "SHOP_ID", precision = 22, scale = 0)
	public BigDecimal getShopId() {
		return this.shopId;
	}

	public void setShopId(BigDecimal shopId) {
		this.shopId = shopId;
	}

	@Column(name = "AGENT_ID", precision = 22, scale = 0)
	public BigDecimal getAgentId() {
		return this.agentId;
	}

	public void setAgentId(BigDecimal agentId) {
		this.agentId = agentId;
	}

	@Column(name = "CITY_ID", precision = 22, scale = 0)
	public BigDecimal getCityId() {
		return this.cityId;
	}

	public void setCityId(BigDecimal cityId) {
		this.cityId = cityId;
	}

	@Column(name = "PROVINCE_ID", precision = 22, scale = 0)
	public BigDecimal getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(BigDecimal provinceId) {
		this.provinceId = provinceId;
	}

	@Column(name = "TERMINAL_NO", length = 20)
	public String getTerminalNo() {
		return this.terminalNo;
	}

	public void setTerminalNo(String terminalNo) {
		this.terminalNo = terminalNo;
	}

	@Column(name = "SHOP_NO", length = 20)
	public String getShopNo() {
		return this.shopNo;
	}

	public void setShopNo(String terminalNo) {
		this.terminalNo = terminalNo;
	}
	
	@Column(name = "AGENT_NO", length = 20)
	public String getAgentNo() {
		return this.agentNo;
	}

	public void setAgentNo(String agentNo) {
		this.agentNo = agentNo;
	}

	@Column(name = "CITY_NO", length = 20)
	public String getCityNo() {
		return this.cityNo;
	}

	public void setCityNo(String cityNo) {
		this.cityNo = cityNo;
	}

	@Column(name = "PROVINCE_NO", length = 20)
	public String getProvinceNo() {
		return this.provinceNo;
	}

	public void setProvinceNo(String provinceNo) {
		this.provinceNo = provinceNo;
	}

}
